
name: CI for template-service

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5
        ports:
          - 27017:27017
        options: >-
          --health-cmd="echo 'db.runCommand("ping").ok' | mongo localhost/test --quiet"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and run tests
        run: |
          cd domains/core/template-service
          npm install
          npm test
