openapi: 3.0.0
info:
  title: Webhook Service
  version: 1.0.0
paths:
  /api/webhook/:
    post:
      summary: Webhook event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookEvent'
      responses:
        '200':
          description: Webhook response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
components:
  schemas:
    WebhookEvent:
      type: object
      properties:
        event_type:
          type: string
        payload:
          type: object
      required:
        - event_type
        - payload
    WebhookResponse:
      type: object
      properties:
        success:
          type: boolean
        detail:
          type: string
