### Get all languages
GET http://localhost:3004/languages
Accept: application/json

###

### Add a new language
POST http://localhost:3004/languages
Content-Type: application/json

{
  "code": "fr",
  "name": "French"
}
