name: CI - Language Service

on:
  push:
    paths:
      - 'core/language-service/**'
  pull_request:
    paths:
      - 'core/language-service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: core/language-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
