openapi: 3.0.0
info:
  title: Schedule Service API
  version: "1.0"
  description: REST API for scheduling alert dispatches
servers:
  - url: http://localhost:8082
paths:
  /api/schedules:
    get:
      summary: Get all schedules
      responses:
        "200":
          description: List of schedules
    post:
      summary: Create a schedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
      responses:
        "201":
          description: Schedule created
  /api/schedules/{id}:
    get:
      summary: Get schedule by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Schedule found
        "404":
          description: Not found
    put:
      summary: Update schedule
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
      responses:
        "200":
          description: Schedule updated
        "404":
          description: Not found
    delete:
      summary: Delete schedule
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Deleted
        "404":
          description: Not found
components:
  schemas:
    Schedule:
      type: object
      properties:
        id:
          type: integer
        alertTitle:
          type: string
        scheduledAt:
          type: string
          format: date-time
        status:
          type: string
