events {}

http {
  include       mime.types;
  default_type  application/json;

  sendfile        on;
  keepalive_timeout  65;

  map $http_origin $cors_origin {
    default $http_origin;
  }

  server {
    listen 80;

    add_header 'Access-Control-Allow-Origin' "$cors_origin" always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;

    if ($request_method = OPTIONS) {
      return 204;
    }

    # CORE Services
    location /api/auth/        { 
        proxy_pass http://10.0.0.17:3001/api/auth/; 
        }
    location /api/users/       { proxy_pass http://10.0.0.17:3002/api/users/; }
    location /api/profiles/    { proxy_pass http://10.0.0.17:3003/api/profiles/; }
    location /api/roles/       { proxy_pass http://10.0.0.17:3004/api/roles/; }
    location /api/languages/   { proxy_pass http://10.0.0.17:3005/api/languages/; }

    # ALERTMANG Services
    location /api/alerts/      { proxy_pass http://10.0.0.189:8081/api/alerts/; }
    location /api/geo/         { proxy_pass http://10.0.0.189:8082/api/geo/; }
    location /api/templates/   { proxy_pass http://10.0.0.189:8083/api/templates/; }
    location /api/schedule/    { proxy_pass http://10.0.0.189:8084/api/schedule/; }
    location /api/validation/  { proxy_pass http://10.0.0.189:8085/api/validation/; }

    # DELIVERY Services
    location /api/email/       { proxy_pass http://10.0.1.84:3006/api/email/; }
    location /api/sms/         { proxy_pass http://10.0.1.84:3007/api/sms/; }
    location /api/push/        { proxy_pass http://10.0.1.84:3008/api/push/; }
    location /api/logs/        { proxy_pass http://10.0.1.84:3009/api/logs/; }
    location /api/retry/       { proxy_pass http://10.0.1.84:3010/api/retry/; }

    # NOTIFICATION Services
    location /api/notification/ { proxy_pass http://10.0.0.206:4103/api/notification/; }
    location /api/channel/      { proxy_pass http://10.0.0.206:4102/api/channel/; }
    location /api/broadcast/    { proxy_pass http://10.0.0.206:4101/api/broadcast/; }
    location /api/retry-engine/ { proxy_pass http://10.0.0.206:4104/api/retry/; }
    location /api/socket/       {
      proxy_pass http://10.0.0.206:4105/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
    }

    # EXTERNAL Services
    location /api/channel-validator/ { proxy_pass http://172.31.81.43:4304/api/channel-validator/; }
    location /api/external-push/    { proxy_pass http://172.31.81.43:4303/api/external-push/; }
    location /api/graphql/          { proxy_pass http://172.31.81.43:4302/api/graphql/; }
    location /api/soap/             { proxy_pass http://172.31.81.43:4301/api/soap/; }
    location /api/webhook/          { proxy_pass http://172.31.81.43:4305/api/webhook/; }

    # REPORT Services
    location /api/audit/        { proxy_pass http://10.0.1.197:4201/api/audit/; }
    location /api/feedback/     { proxy_pass http://10.0.1.197:4202/api/feedback/; }
    location /api/metrics/      { proxy_pass http://10.0.1.197:4203/api/metrics/; }
    location /api/report/       { proxy_pass http://10.0.1.197:4204/api/report/; }
    location /api/analyze/      { proxy_pass http://10.0.1.197:4205/api/analyze/; }
  }
}
