name: CI - soap-consumer

on:
  push:
    paths:
      - 'domains/external/soap-consumer/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: deasla_mysql
          MYSQL_USER: deasla
          MYSQL_PASSWORD: pass
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Load env variables
        run: |
          set -a
          source domains/external/soap-consumer/.env
          set +a

      - name: Install dependencies
        run: |
          cd domains/external/soap-consumer
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd domains/external/soap-consumer
          python -m unittest discover
