openapi: 3.0.0
info:
  title: Profile Service API
  version: "1.0"
  description: REST API for user profile management
servers:
  - url: http://localhost:3003
paths:
  /api/profiles:
    get:
      summary: Get all profiles
      responses:
        "200":
          description: List of profiles
    post:
      summary: Create a profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        "201":
          description: Profile created
  /api/profiles/{id}:
    get:
      summary: Get profile by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Profile found
        "404":
          description: Not found
    put:
      summary: Update profile
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        "200":
          description: Profile updated
        "404":
          description: Not found
    delete:
      summary: Delete profile
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted
        "404":
          description: Not found
components:
  schemas:
    Profile:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        fullName:
          type: string
        phone:
          type: string
