events {}

http {
  include       mime.types;
  default_type  application/json;

  sendfile        on;
  keepalive_timeout  65;

  map $http_origin $cors_origin {
    default $http_origin;
  }

  server {
    listen 80;

    add_header 'Access-Control-Allow-Origin' "$cors_origin" always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;

    if ($request_method = OPTIONS) {
      return 204;
    }

    # CORE Services
    location /api/auth/        { 
        proxy_pass http://10.0.0.17:3001/; 
        }
    location /api/users/       { 
        proxy_pass http://10.0.0.17:3002/;
         }
    location /api/profiles/    { 
        proxy_pass http://10.0.0.17:3003/; 
        }
    location /api/roles/       { 
        proxy_pass http://10.0.0.17:3004/; 
        }
    location /api/languages/   { 
        proxy_pass http://10.0.0.17:3005/; 
        }

    # ALERTMANG Services
    location /api/alerts/      { 
        proxy_pass http://10.0.0.189:8081/; 
        }
    location /api/geo/         { 
        proxy_pass http://10.0.0.189:8082/; 
        }
    location /api/templates/   {
         proxy_pass http://10.0.0.189:8083/; 
        }
    location /api/schedule/    { 
        proxy_pass http://10.0.0.189:8084/;
        }
    location /api/validation/  { 
        proxy_pass http://10.0.0.189:8085/;
    }

    # DELIVERY Services
    location /api/email/       { 
        proxy_pass http://10.0.1.84:3006/; 
        }
    location /api/sms/         { 
        proxy_pass http://10.0.1.84:3007/;
         }
    location /api/push/        { 
        proxy_pass http://10.0.1.84:3008/;
         }
    location /api/logs/        { 
        proxy_pass http://10.0.1.84:3009/;
         }
    location /api/retry/       { 
        proxy_pass http://10.0.1.84:3010/;
         }

    # NOTIFICATION Services
    location /api/notification/ { 
        proxy_pass http://10.0.0.206:4103/;
         }
    location /api/channel/      { 
        proxy_pass http://10.0.0.206:4102/;
         }
    location /api/broadcast/    { 
        proxy_pass http://10.0.0.206:4101/;
         }
    location /api/retry-engine/ { 
        proxy_pass http://10.0.0.206:4104/; 
        }
    location /api/socket/       {
      proxy_pass http://10.0.0.206:4105/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
    }

    # EXTERNAL Services
    location /api/channel-validator/ { 
        proxy_pass http://172.31.81.43:4304/; 
        }
    location /api/external-push/    { 
        proxy_pass http://172.31.81.43:4303/; 
        }
    location /api/graphql/          { 
        proxy_pass http://172.31.81.43:4302/;
        }
    location /api/soap/             { 
        proxy_pass http://172.31.81.43:4301/;
         }
    location /api/webhook/          { 
        proxy_pass http://172.31.81.43:4305/; 
        }

    # REPORT Services
    location /api/audit/        { 
        proxy_pass http://10.0.1.197:4201/; 
        }
    location /api/feedback/     { 
        proxy_pass http://10.0.1.197:4202/; 
        }
    location /api/metrics/      { 
        proxy_pass http://10.0.1.197:4203/; 
        }
    location /api/report/       { 
        proxy_pass http://10.0.1.197:4204/; 
        }
    location /api/analyze/      { 
        proxy_pass http://10.0.1.197:4205/; 
        }
  }
}
