name: CI - channel-service

on:
  push:
    paths:
      - 'domains/notification/channel-service/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Load env variables
        run: |
          set -a
          source domains/notification/channel-service/.env
          set +a

      - name: Run tests
        run: |
          cd domains/notification/channel-service
          go test ./...
