name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v1
    - name: Install dependencies and test
      run: |
        echo "Running test for python in profile-service"
        pip install -r requirements.txt && pytest