openapi: 3.0.0
info:
  title: Validation Service API
  version: "1.0"
  description: REST API for validating and logging alerts
servers:
  - url: http://localhost:8085
paths:
  /api/validations:
    get:
      summary: Get all validation results
      responses:
        "200":
          description: List of results
    post:
      summary: Validate an alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationResult'
      responses:
        "201":
          description: Validation result created
  /api/validations/{id}:
    get:
      summary: Get validation result by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Result found
        "404":
          description: Not found
    delete:
      summary: Delete result
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Deleted
        "404":
          description: Not found
components:
  schemas:
    ValidationResult:
      type: object
      properties:
        id:
          type: integer
        alertTitle:
          type: string
        status:
          type: string
        details:
          type: string
